language: php

php:
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

#addons:
#  postgresql: "9.3"
#
services:
  - memcached
  - redis-server

before_install:
  - composer global require phpunit/phpunit ^8||^9
#  - sh -e build/travis/scripts/apt-get.sh
#  - sh -e build/travis/scripts/apache2-vhost.sh
#  - sh -e build/travis/scripts/apache2-configure.sh
  - sh -e build/travis/scripts/libsodium.sh

before_script:
  - sh -e build/travis/scripts/pecl-libsodium.sh || true
  - composer install
#  - phpenv rehash

script:
  - /home/travis/.config/composer/vendor/bin/phpunit -v --configuration phpunit.travis.xml
